# Generated by Django 3.2.15 on 2022-10-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_profile_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='_backend_profile_following_+', to='backend.Profile'),
        ),
    ]
