# Generated by Django 3.2.15 on 2022-10-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20221025_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='profile_cover'),
        ),
    ]
