# Generated by Django 3.2.15 on 2022-10-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_profile_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_image',
        ),
    ]
