# Generated by Django 3.2.15 on 2022-11-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20221103_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ManyToManyField(related_name='likes', to='backend.Post'),
        ),
    ]
