# Generated by Django 3.2.15 on 2022-11-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
