# Generated by Django 3.2.15 on 2022-11-10 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.comment'),
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ManyToManyField(related_name='likes', to='backend.Comment'),
        ),
    ]
