# Generated by Django 3.2.15 on 2022-11-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_backend_profile_following_+', to='backend.Profile'),
        ),
    ]
