# Generated by Django 3.2.15 on 2022-11-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(null=True, related_name='followers', to='backend.Profile'),
        ),
    ]
