# Generated by Django 3.2.15 on 2022-11-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='backend.profile'),
        ),
        migrations.AlterField(
            model_name='like',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.profile'),
        ),
    ]
