# Generated by Django 3.2.15 on 2022-11-17 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.profile'),
        ),
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='likes', to='backend.Comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='likes', to='backend.Post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.profile'),
        ),
    ]
