# Generated by Django 3.2.15 on 2023-08-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_post_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, default='profile/default.jpg', null=True, upload_to='profile_cover'),
        ),
    ]
