# Generated by Django 3.2.15 on 2022-11-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20221117_1538'),
        ('chat', '0003_auto_20221129_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(related_name='rooms', to='backend.Profile'),
        ),
    ]
