# Generated by Django 3.2.15 on 2022-12-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20221205_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver_Profile',
            new_name='receiver_profile',
        ),
    ]
